[package]
name = "laboratory_1_2"
version = "1.0.0"
edition = "2021"
authors = "Dmitriy-U"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.6"
